site_name: "KayakTransaction CSV Processing"
site_description: "User-friendly documentation powered by MkDocs."
# site_url: "https://documentation-using-ai-agent.readthedocs.io"

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  language: en

extra:
  favicon: assets/img/favicon.ico

repo_url: "https://github.com/SHINO-01/Documentation-using-RTD-MKDocs"

plugins:
  - awesome-pages  # Automatically organizes navigation based on the folder structure
  - search
  - gen-files:
      scripts:
        - scripts/generate_TOC.py
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.extra
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
